/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package batalha.naval;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Cat
 */
public class Manual extends javax.swing.JFrame {

    /**
     * Creates new form Manual
     */
    public Manual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonJogarMan = new javax.swing.JButton();
        jLabelManual = new javax.swing.JLabel();
        jLabelM1 = new javax.swing.JLabel();
        jLabelM2 = new javax.swing.JLabel();
        jLabelM3 = new javax.swing.JLabel();
        jLabelM4 = new javax.swing.JLabel();
        jLabelM5 = new javax.swing.JLabel();
        jLabelM6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jButtonVoltar.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonJogarMan.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButtonJogarMan.setText("Jogar");
        jButtonJogarMan.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonJogarMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogarManActionPerformed(evt);
            }
        });

        jLabelManual.setFont(new java.awt.Font("Tekton Pro Cond", 1, 26)); // NOI18N
        jLabelManual.setForeground(new java.awt.Color(255, 255, 255));
        jLabelManual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelManual.setText("Instruções:");
        jLabelManual.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelM1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabelM1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelM1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM1.setText("- O jogo tem como objetivo afundar todos os Navios Militares dentro do limite de tiros fornecidos.");
        jLabelM1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelM2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabelM2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelM2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM2.setText("- Existem 2 tipos de Navios Civis: Paquete e Porta-Contentores.");
        jLabelM2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelM3.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabelM3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelM3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM3.setText("- Existem 3 tipos de Navios Militares: Submarinos, Cruzadores e Porta-Aviões.");
        jLabelM3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelM4.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabelM4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelM4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM4.setText("- Se afundar qualquer um dos Navios Civis, perde o jogo de imediato!");
        jLabelM4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelM5.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabelM5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelM5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM5.setText("- Cada tipo de navio tem uma representação diferente em tamanho, cor e formato. ");
        jLabelM5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelM6.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabelM6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelM6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelM6.setText("- Ganha pontos por cada tiro certeiro mas perde pontos de cada vez que atingir um navio civil.");
        jLabelM6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButtonJogarMan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addComponent(jLabelM1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelM2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelM3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelM4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelM5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelM6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelManual)
                .addGap(18, 18, 18)
                .addComponent(jLabelM1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelM2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelM3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelM4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelM5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelM6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonJogarMan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        BemVindo v = new BemVindo();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonJogarManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogarManActionPerformed
        // TODO add your handling code here:
        Dificuldade j = new Dificuldade();
        j.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonJogarManActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJogarMan;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelM1;
    private javax.swing.JLabel jLabelM2;
    private javax.swing.JLabel jLabelM3;
    private javax.swing.JLabel jLabelM4;
    private javax.swing.JLabel jLabelM5;
    private javax.swing.JLabel jLabelM6;
    private javax.swing.JLabel jLabelManual;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
